FROM python:alpine
WORKDIR /api

ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9
RUN apk add --no-cache build-base openssl openblas-dev ffmpeg sox libffi-dev libsndfile-dev
COPY requirements.m1.txt .
COPY *.pem .
COPY ./app /api/app
RUN pip install -r requirements.m1.txt && pip install numpy --no-use-pep517

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000","--ssl-keyfile=./key.pem" ,"--ssl-certfile=./cert.pem"]
